// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itpethrycbjxgyfjujhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0cGV0aHJ5Y2JqeGd5Zmp1amhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3MDA5OTAsImV4cCI6MjA1MzI3Njk5MH0.DumQVVrLSxAkeDk8V0IKkon7PANuoMhZDkLAkaIBpJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);